language: python
os:
- linux
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
    - g++-4.8-multilib
    - gcc-multilib
    - build-essential
    - scons
    - swig
python:
  - "2.7"
  - "3.4"
  - "3.6"
  - "3.6-dev" # 3.6 development branch
  - "nightly" # currently points to 3.7-dev
before_install:
- git clone https://github.com/jgarff/rpi_ws281x.git /tmp/rpi_ws281x
- scons /tmp/rpi_ws281x/
install: "pip install -r requirements.txt"
script: pytest tests/