language: python
os:
- linux
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
    - g++-4.8-multilib
    - gcc-multilib
    - build-essential
    - scons
    - swig
    - python-setuptools
python:
  - "2.7"
  - "3.4"
  - "3.6"
  - "3.6-dev" # 3.6 development branch
  - "nightly" # currently points to 3.7-dev
before_install:
  - git clone https://github.com/pimoroni/unicorn-hat ~/unicorn-hat/
  - cd ~/unicorn-hat/
  - cd library/rpi-ws281x
  - sudo python setup.py install
  - cd ../..
  - cd library/UnicornHat
  - sudo python setup.py install
  - cd ../..
install: 
  - cd ~/claudinha-io/claudinha-module
  - "pip install -r requirements.txt"
script: pytest tests/